title: "Line By Line"
title_separator          : "|"
subtitle                 : "천리길도 한걸음 부터"
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog about technology, development, and insights.
baseurl: "" # project site인 경우 "/리포지토리명"
url: "https://ech97.github.io" # the base hostname & protocol for your site
github_username: ech97
search: true
logo: "/assets/favicon/favicon.svg"

author:
  name   : "Chanhyun Lee"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Software engineer with passion for technology and innovation."
  location  : "Suwon, Republic of Korea"
  email  : "ech97@naver.com"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ech97"
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ech97"
copyright: "© 2025 Chanhyun Lee. All rights reserved."


# Build settings
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark
after_footer_scripts:
  - https://cdn.jsdelivr.net/npm/clipboard@2/dist/clipboard.min.js
  - assets/js/clipboardrouge.js

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Seoul

# Including
include:
  - _pages
  # - assets/css/custom.css

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# disqus 댓글기능 활성화
repository: "ech97/ech97.github.io"
comments:
  provider               : "utterances" # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : "ech97-github-io"
  discourse:
    server               : # https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963 , e.g.: meta.discourse.org
  facebook:
    # https://developers.facebook.com/docs/plugins/comments
    appid                :
    num_posts            : # 5 (default)
    colorscheme          : # "light" (default), "dark"
  utterances:
    theme                : "github-light" # "github-light" (default), "github-dark"
    issue_term           : "pathname" # "pathname" (default)
  giscus:
    repo_id              : # Shown during giscus setup at https://giscus.app
    category_name        : # Full text name of the category
    category_id          : # Shown during giscus setup at https://giscus.app
    discussion_term      : # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : # '1' for enabled (default), '0' for disabled
    theme                : # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
  staticman:
    branch               : # "master"
    endpoint             : # "https://{your Staticman v3 API}/v3/entry/github/"
reCaptcha:
  siteKey                :
  secret                 :
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : # true, false (default)
search                   : true # true, false (default)
search_full_content      : true # true, false (default)
search_provider          : # lunr (default), algolia, google
algolia:
  application_id         : # YOUR_APPLICATION_ID
  index_name             : # YOUR_INDEX_NAME
  search_only_api_key    : # YOUR_SEARCH_ONLY_API_KEY
  powered_by             : # true (default), false
google:
  search_engine_id       : # YOUR_SEARCH_ENGINE_ID
  instant_search         : # false (default), true
# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  : 
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

date_format: "%Y-%m-%d"

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
  collections:
    - articles


collections:
  articles:
    output: true
    permalink:  /articles/:name/

defaults:
  # - scope:
  #     path: ""
  #     type: articles
  #   values:
  #     layout: single
  #     author_profile: true
  #     comments: true
  #     related: true
  #     comments: true
  #     use_math: true
  #     toc: true
  #     toc_sticky: true
  #     show_date: true
  #     sidebar:
  #       nav: "sidebar-category"
  - scope:
      path: ""
    values:
      header:
        overlay_image: "/assets/images/header.png"
        overlay_filter: 0.5
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      sidebar:
        nav: "sidebar-category"
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      comments: true
      related: true
      comments: true
      use_math: true
      toc: true
      toc_sticky: true
      show_date: true
      categories: Null
      sidebar:
        nav: "sidebar-category"