
title: "Done is better than Perfect"
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog about technology, development, and insights.
baseurl: "" # project site인 경우 "/리포지토리명"
twitter_username: 
github_username: ech97
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Seoul

# Including
include:
  - _pages
  # - assets/css/custom.css

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Chanhyun Lee"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Software engineer with passion for technology and innovation."
  location  : "Seoul, Republic of Korea"
  email  : "ech97@naver.com"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://chanhyun.lee.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ech97"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ech97"

collections:
  kernel-modules:           # 커널 모듈 개발 전용 컬렉션
    output: true
    permalink: /kernel-modules/:title/
  ai-research:              # AI 모델 리서치 전용 컬렉션
    output: true
    permalink: /ai-research/:title/

defaults:
  - scope:
      path: ""              # 루트 전체
      type: kernel-modules  # 컬렉션 이름
    values:
      layout: single
      header:
        image: "/assets/images/banners/kernel-modules/banner.jpg"
        overlay_image: true
        overlay_opacity: 0.6
      sidebar:
        nav: "main"
        author_profile: true

  - scope:
      path: ""
      type: ai-research
    values:
      layout: single
      header:
        image: "/assets/images/banners/ai-research/banner.jpg"
        overlay_image: true
        overlay_opacity: 0.6
      sidebar:
        nav: "main"
        author_profile: true

  # 모든 페이지에 author 프로필과 네비게이션 사이드바 표시
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "main"
      author_profile: true

  # 모든 포스트에 작성일, author_profile 표시
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      author_profile: true
      sidebar:
        nav: "main"

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

# plugins:
#   - jekyll-archives

# jekyll-archives:
#   enabled:
#     - categories
#   layouts:
#     category: category
#   permalinks:
#     category: /categories/:name/


# # Analytics, SEO 추가 예시
# analytics:
#   provider: "google"
#   google:
#     tracking_id: "UA-XXXXXXXXX-X"
# google_site_verification: "YOUR_VERIFICATION_CODE"



# comments:
#   provider: "giscus"  # utterances, disqus, staticman 등 지원
#   giscus:
#     repo: "YOUR_USERNAME/YOUR_REPO"
#     repo_id: "REPO_ID"
#     category: "Announcements"
#     category_id: "CATEGORY_ID"