
title: "Done is better than Perfect"
description: >- # this means to ignore newlines until "baseurl:"
  Personal blog about technology, development, and insights.
baseurl: "" # project site인 경우 "/리포지토리명"
twitter_username: 
github_username: ech97
minimal_mistakes_skin: air
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Seoul

include:
  - _pages

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-lunr-js-search

# include custom CSS
include:
  - assets/css/custom.scss

author:
  name   : "Chanhyun Lee"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Software engineer with passion for technology and innovation."
  location  : "Seoul, Republic of Korea"
  email  : "ech97@naver.com"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://chanhyun.lee.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ech97"

# # Analytics, SEO 추가 예시
# analytics:
#   provider: "google"
#   google:
#     tracking_id: "UA-XXXXXXXXX-X"
# google_site_verification: "YOUR_VERIFICATION_CODE"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ech97"


# ─── collections 정의 ────────────────────────────────────
collections:
  kernel-modules:           # 커널 모듈 개발 전용 컬렉션
    output: true
    permalink: /kernel/:title/
  ai-research:              # AI 모델 리서치 전용 컬렉션
    output: true
    permalink: /research/:title/

# ─── 기본값(defaults)으로 각 컬렉션에 배너 자동 지정 ───────────────
defaults:
  # ── 커널 모듈 글의 기본 front matter ──
  - scope:
      path: ""              # 루트 전체
      type: kernel-modules  # 컬렉션 이름
    values:
      layout: post
      header:
        # image: "/assets/images/banners/kernel-modules/banner.jpg"
        overlay_image: true
        overlay_opacity: 0.6
      sidebar:
        nav: "main"
        author_profile: true

  # ── AI 모델 리서치 글의 기본 front matter ──
  - scope:
      path: ""
      type: ai-research
    values:
      layout: post
      header:
        # image: "/assets/images/banners/ai-research/banner.jpg"
        overlay_image: true
        overlay_opacity: 0.6
      sidebar:
        nav: "main"
        author_profile: true

  # 모든 페이지에 author 프로필과 네비게이션 사이드바 표시
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "main"
      author_profile: true

  # 모든 포스트에 작성일, author_profile 표시
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      author_profile: true
      sidebar:
        nav: "main"

# comments:
#   provider: "giscus"  # utterances, disqus, staticman 등 지원
#   giscus:
#     repo: "YOUR_USERNAME/YOUR_REPO"
#     repo_id: "REPO_ID"
#     category: "Announcements"
#     category_id: "CATEGORY_ID"

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/



# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
